dist: xenial
language: cpp
cache: ccache
matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - cmake-data
            - qt5-default
      env:
        -CXX_COMPILER=g++-5
        -C_COMPILER=gcc-5
    - os: osx
      osx_image: xcode11.4
      env:
        -CXX_COMPILER=g++-5
        -C_COMPILER=gcc-5
script:
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        export PATH=/usr/local/opt/qt/bin:$PATH;
    fi
  - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER  .. && make -j3
after_success:
  - cd ../sample && $CXX_COMPILER -std=c++11 -O3 main_clock.cpp -o test_clock && ./test_clock
  - ./build_express_test.sh
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew install gcc5;
        brew install qt;
        brew link --force qt;
    fi
